tlebeitsuk/hoster

package.json
pnpm-lock.yaml
src/app/dashboard/page.tsx
src/app/globals.css
src/components/sidebar-app.tsx
src/components/sidebar-main.tsx
src/components/sidebar-switcher.tsx
src/components/sidebar-user.tsx
src/components/ui/avatar.tsx
src/components/ui/breadcrumb.tsx
src/components/ui/button.tsx
src/components/ui/collapsible.tsx
src/components/ui/dropdown-menu.tsx
src/components/ui/input.tsx
src/components/ui/separator.tsx
src/components/ui/sheet.tsx
src/components/ui/sidebar.tsx
src/components/ui/skeleton.tsx
src/components/ui/tooltip.tsx
src/hooks/use-mobile.tsx
tailwind.config.ts

Adds initial dashboard
Completes #6

Add dashboard

---

package.json
pnpm-lock.yaml
src/app/projects/new/page.tsx
src/components/ui/label.tsx

missing label

---

src/app/dashboard/[projectId]/page.tsx
src/app/dashboard/page.tsx
src/app/page.tsx
src/components/profile.tsx
src/components/sidebar-user.tsx

Add landing page

---

src/app/login/page.tsx
src/components/login.tsx

Redirect to dashboard when already signed in

---

package.json
src/app/layout.tsx
src/app/page.tsx
src/components/sidebar-theme-toggle.tsx
src/components/sidebar-user.tsx
src/components/theme-toggle.tsx
src/hooks/theme-provider.tsx

- Byt till system, light och dark mode
- Toggle finns vid sidebar-user.tsx och page.tsx (/) footer
#39
(/login behövs ändringar #42)

Theme Switcher

---

src/app/globals.css
src/components/sidebar-app.tsx

shadcn sidebar kan inte ändras med className och i stället används globals.css med hsl values
- https://ui.shadcn.com/docs/components/sidebar#theming
Closes #45

Fix background color

---

src/data/account/delete-account.ts
src/data/projects/new-project.ts
src/lib/auth.ts
src/lib/prisma.ts

Det görs en prisma klient enligt:
- https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices
Closes #43

Optimise prisma.ts

---

src/app/dashboard/[projectId]/[serverName]/page.tsx
src/app/dashboard/[projectId]/page.tsx
src/app/dashboard/layout.tsx
src/app/dashboard/page.tsx
src/components/profile.tsx

- Det här lagar automatiskt breadcrumbs med url men det är inte bästa sättet för /dashboard/[projectId] visar "Dashboard > 1".
Men det fungerar för tillfället.
Closes #46 and #58
Combines pull request #59

URL Breadcrumbs

---

src/data/projects/get-servers.ts

changed getServers() function

---

src/components/profile.tsx
src/data/account/delete-account.ts

Säger "Cannot delete account. You have existing projects." om man har projects och försöker delete account
Closes #48

Fix error message

---

package.json
src/app/dashboard/[projectId]/page.tsx
src/app/dashboard/[projectId]/settings/page.tsx
src/components/project-settings.tsx
src/components/ui/alert-dialog.tsx
src/components/ui/sidebar.tsx

Initial project settings
Closes #54

Project settings

---

pnpm-lock.yaml
src/app/dashboard/[projectId]/settings/page.tsx
src/components/project-settings.tsx

Project name to settings

---

src/app/dashboard/[projectId]/[serverName]/page.tsx
src/app/dashboard/[projectId]/page.tsx
src/app/dashboard/[projectId]/server/new/page.tsx
src/components/new-server.tsx
src/data/projects/new-server.ts

- Ny server i /server/new
- Server action i new-server.ts
Closes #12

New server

---

src/components/sidebar-projects.tsx

Make selected project highlighted

---

src/components/project-settings.tsx

Add project description setting

---

src/app/dashboard/[projectId]/page.tsx
src/data/projects/get-projects.ts

Adds project description and title

---

src/components/delete-server-button.tsx

Alert dialog for delete server

---

src/app/dashboard/[projectId]/page.tsx

Cards for empty project

---

src/components/project-settings.tsx
src/components/ui/textarea.tsx

Fix description label

---

pnpm-lock.yaml
src/app/dashboard/[projectId]/page.tsx

Empty project revert

---

package.json
src/components/new-server.tsx
src/components/ui/radio-group.tsx

Move templates to new server

---

src/app/dashboard/[projectId]/[serverName]/page.tsx

- Fixed it returning NaN when its not running
- Made them look alike

Natalie memory cpu cards fix

---

src/app/page.tsx
src/components/login.tsx
src/hooks/theme-provider.tsx

Match colors

---

src/components/project-settings.tsx

Implemented toast sonner

---

pnpm-lock.yaml
src/components/new-server.tsx

Closes #112 and #115 
- Generates random password when you click postgresql or mysql
- Can also do your own password

Add Password for Services

---

src/app/dashboard/page.tsx
src/app/types.d.ts
src/components/dashboard.tsx

- Tell user that they have no projects if 0
- Shows latest 9 projects
- Closes #139

Improved /dashboard

---

src/components/toggle-server-status.tsx
src/data/projects/toggle-server.ts

fixed server status color

---

src/app/dashboard/[projectId]/page.tsx

Server list refreshes when new server is added

---

src/app/dashboard/[projectId]/[serverName]/page.tsx
src/data/projects/delete-project.ts
src/data/projects/new-project.ts
src/lib/incus.ts

Closes #133 
Closes #80
Closes #87

Create and delete project in Incus

---

src/app/dashboard/[projectId]/settings/page.tsx
src/app/types.d.ts
src/components/project-settings.tsx

Closes #84 
- Can't delete project if there is servers in it
- Fix type errors

Check if there is servers in project before deleting

---

src/app/dashboard/[projectId]/page.tsx
src/data/projects/delete-project.ts
src/data/projects/delete-server.ts
src/data/projects/get-servers.ts
src/data/projects/new-server.ts
src/data/projects/project-settings.ts
src/data/projects/toggle-server.ts

Added user authorization checks in `deleteProject`, `deleteServer`, `getServers`, `newServer`, `renameProject`, `changeProjectDescription`, and `toggleServer` functions to ensure the user has access to the project before performing operations
Closes #145

Secure data layer
